(() => {
  'use strict';
  const KEY='botanic-wms-v5', OLD='botanic-wms-v4';
  const seed={meta:{nextPack:8,nextMovement:6,nextMaterial:6,nextCount:1},settings:{expiryWarningMonths:2},materials:[
    {id:'S-001',name:'Ashwagandha KSM-66',min:5000},{id:'S-002',name:'Boswellia serrata',min:4000},{id:'S-003',name:'Rozchodnice růžová',min:3500},{id:'S-004',name:'Kotvičník zemní',min:2500},{id:'S-005',name:'Maca',min:3000}],
    boxes:Array.from({length:20},(_,i)=>({id:String(i+1)})),positions:Array.from({length:4},(_,r)=>Array.from({length:10},(_,c)=>({id:`${String.fromCharCode(65+r)}${c+1}`}))).flat(),
    packs:[{id:'P-2026-001',material:'S-001',lot:'AK66-260801',expiry:'08/27',qty:2400,initialQty:2800,box:'1',position:'A1',packState:'nový'},{id:'P-2026-002',material:'S-001',lot:'AK66-260812',expiry:'08/27',qty:1800,initialQty:2100,box:'2',position:'A2',packState:'otevřený'},{id:'P-2026-003',material:'S-002',lot:'BS-260802',expiry:'08/27',qty:4100,initialQty:4100,box:'3',position:'A3',packState:'nový'},{id:'P-2026-004',material:'S-003',lot:'RR-260805',expiry:'08/27',qty:3200,initialQty:3200,box:'4',position:'B1',packState:'nový'},{id:'P-2026-005',material:'S-004',lot:'KT-260808',expiry:'08/27',qty:2100,initialQty:2100,box:'5',position:'B2',packState:'otevřený'},{id:'P-2026-006',material:'S-005',lot:'MA-260810',expiry:'08/27',qty:2900,initialQty:2900,box:'6',position:'B3',packState:'nový'},{id:'P-2026-007',material:'S-002',lot:'BS-260818',expiry:'08/27',qty:2200,initialQty:2200,box:'7',position:'C1',packState:'nový'}],
    movements:[{id:'M-001',date:'2026-08-30T08:50:00',type:'Příjem',pack:'P-2026-007',qty:2200,from:'Příjem',to:'C1',reason:'Příjem zásoby'},{id:'M-002',date:'2026-08-30T08:10:00',type:'Výdej',pack:'P-2026-002',qty:-300,from:'A2',to:'Výdej',reason:'Výdej'},{id:'M-003',date:'2026-08-29T16:31:00',type:'Přesun',pack:'P-2026-005',qty:0,from:'A4',to:'B2',reason:'Změna pozice'},{id:'M-004',date:'2026-08-29T13:05:00',type:'Výdej',pack:'P-2026-001',qty:-400,from:'A1',to:'Výdej',reason:'Výdej'},{id:'M-005',date:'2026-08-28T11:40:00',type:'Příjem',pack:'P-2026-006',qty:2900,from:'Příjem',to:'B3',reason:'Příjem zásoby'}],counts:[]};
  const s={view:'inventory',q:'',material:'ALL',packState:'ALL',page:1,per:20,sort:'material',dir:'asc',selected:new Set(),theme:localStorage.getItem('botanic-theme')||'dark'};
  const $=q=>document.querySelector(q), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const clone=v=>JSON.parse(JSON.stringify(v)); const fmt=n=>new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:2}).format(Number(n)||0);
  let db=load();
  function normExp(v){const x=String(v??'').trim(),iso=x.match(/^(\d{4})-(\d{2})-\d{2}/),m=x.match(/^(\d{1,2})[\/.\-](\d{2}|\d{4})$/);if(iso)return`${iso[2]}/${iso[1].slice(-2)}`;return m?`${String(Math.min(12,Math.max(1,+m[1]))).padStart(2,'0')}/${m[2].slice(-2)}`:x}
  function normalize(d){d??=clone(seed);d.meta??=clone(seed.meta);d.settings??=clone(seed.settings);d.materials??=[];d.boxes??=[];d.positions??=[];d.packs??=[];d.movements??=[];d.counts??=[];d.boxes=d.boxes.map((b,i)=>({id:String(b.id??i+1).replace(/^B-/i,'')}));for(const p of d.packs){p.qty=Math.max(0,+p.qty||0);p.initialQty=Math.max(p.qty,+p.initialQty||p.qty);p.box=String(p.box??'').replace(/^B-/i,'');p.packState=p.packState==='opened'||p.packState==='otevřený'?'otevřený':'nový';p.expiry=normExp(p.expiry)}return d}
  function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD)||'null'))}catch{return clone(seed)}}
  function save(msg){localStorage.setItem(KEY,JSON.stringify(db));if(msg){const q=JSON.parse(localStorage.getItem('botanic-wms-outbox-v2')||'[]');q.push({at:new Date().toISOString(),action:msg});localStorage.setItem('botanic-wms-outbox-v2',JSON.stringify(q))}render()}
  function mat(id){return db.materials.find(x=>x.id===id)}function pack(id){return db.packs.find(x=>x.id===id)}function active(){return db.packs.filter(x=>x.qty>0)}function stock(){return active().reduce((a,x)=>a+x.qty,0)}
  function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;$('#toastStack').append(e);setTimeout(()=>e.remove(),2200)}
  function modal(html){const d=$('#actionDialog');d.innerHTML=html;d.showModal()}function close(){if($('#actionDialog').open)$('#actionDialog').close()}
  function input(label,name,value='',type='text',extra=''){return`<label class="field"><span>${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
  function sel(label,name,items,value){return`<label class="field"><span>${esc(label)}</span><select name="${name}">${items.map(x=>`<option value="${esc(x.value)}" ${x.value===value?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label>`}
  function next(key,prefix){const n=+db.meta[key]||1;db.meta[key]=n+1;return prefix+String(n).padStart(3,'0')}function nextPack(){return`P-${new Date().getFullYear()}-${String((+db.meta.nextPack||1)).padStart(3,'0')}`}
  function validatePack(p){return p.qty>=0&&p.initialQty>=p.qty&&/^\d{2}\/\d{2}$/.test(p.expiry)&&!!p.lot&&!!mat(p.material)&&db.boxes.some(b=>b.id===p.box)&&db.positions.some(x=>x.id===p.position)}
  function ensure(){const bad=db.packs.find(p=>!validatePack(p));if(bad){toast(`Neplatný záznam ${bad.id}`);return false}return true}
  function expRank(v){const m=String(v).match(/^(\d{2})\/(\d{2})$/);return m?(2000+ +m[2])*12+ +m[1]:1e9}function expState(v){const d=expRank(v);if(d===1e9)return'neznámá';const n=new Date(),cur=n.getFullYear()*12+n.getMonth()+1,diff=d-cur;return diff<0?'po expiraci':diff<=2?'brzy expiruje':'OK'}
  function rows(){let a=active(),q=s.q.toLocaleLowerCase('cs-CZ');a=a.filter(p=>{const hay=[p.id,p.lot,p.expiry,p.box,p.position,p.packState,mat(p.material)?.name].join(' ').toLocaleLowerCase('cs-CZ');return(!q||hay.includes(q))&&(s.material==='ALL'||p.material===s.material)&&(s.packState==='ALL'||p.packState===s.packState)});a.sort((x,y)=>{const k=s.sort,z=k==='material'?(mat(x.material)?.name||''):k==='qty'?x.qty:k==='expiry'?expRank(x.expiry):x[k]||'',w=k==='material'?(mat(y.material)?.name||''):k==='qty'?y.qty:k==='expiry'?expRank(y.expiry):y[k]||'',r=z>w?1:z<w?-1:0;return s.dir==='asc'?r:-r});return a}
  function summary(){const alerts=active().filter(p=>expState(p.expiry)!=='OK').length;$('#summary').innerHTML=`<div class="metric"><small>Aktuální zásoba</small><strong>${fmt(stock())} g</strong><span>${fmt(stock()/1000)} kg celkem</span></div><div class="metric"><small>Aktivní pytle</small><strong>${active().length}</strong><span>${db.packs.length} evidovaných</span></div><div class="metric"><small>Pozice</small><strong>${new Set(active().map(p=>p.position)).size}</strong><span>${db.positions.length} dostupných</span></div><div class="metric"><small>Pozornost</small><strong>${alerts}</strong><span>${alerts?'expirace / kontrola':'bez upozornění'}</span></div>`}
  function render(){document.documentElement.dataset.theme=s.theme;summary();document.querySelectorAll('.view').forEach(v=>v.hidden=true);const v=$('#view-'+s.view);if(v)v.hidden=false;document.querySelectorAll('[data-simple-view]').forEach(b=>b.classList.toggle('active',b.dataset.simpleView===s.view));if(s.view==='inventory')inventory();if(s.view==='warehouse')warehouse();if(s.view==='movements')movements();if(s.view==='materials')materials();if(s.view==='counts')counts();pager();$('#connectionState').textContent=navigator.onLine?'Lokální data · online':'Lokální data · offline'}
  function inventory(){const a=rows(),pages=Math.max(1,Math.ceil(a.length/s.per));s.page=Math.min(Math.max(1,s.page),pages);const vis=a.slice((s.page-1)*s.per,s.page*s.per);$('#view-inventory').innerHTML=`<div class="page-title"><div><div class="eyebrow">SKLAD / EVIDENCE</div><h1>Zásoby</h1><p>Jeden řádek = jedno balení. Váha je vždy v gramech.</p></div><div class="inline-actions"><button class="btn" data-simple="issue">− Výdej</button><button class="btn" data-simple="move">↕ Přesun</button></div></div><div class="toolbar-card"><select id="invMaterial"><option value="ALL">Všechny suroviny</option>${db.materials.map(m=>`<option value="${m.id}" ${s.material===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select><select id="invState"><option value="ALL">Všechny stavy</option><option value="nový" ${s.packState==='nový'?'selected':''}>nový</option><option value="otevřený" ${s.packState==='otevřený'?'selected':''}>otevřený</option></select></div><div class="table-card"><div class="table-scroll"><table><thead><tr><th><input id="selectAll" class="check" type="checkbox"></th><th>ID pytle ↕</th><th>Název suroviny ↕</th><th>Šarže ↕</th><th>Expirace ↕</th><th>Box ↕</th><th>Pozice ↕</th><th>Aktuální hmotnost ↕</th><th>Stav</th><th></th></tr></thead><tbody>${vis.length?vis.map(p=>`<tr data-id="${esc(p.id)}"><td><input class="check row-check" type="checkbox" ${s.selected.has(p.id)?'checked':''}></td><td class="mono"><b>${esc(p.id)}</b></td><td>${esc(mat(p.material)?.name||p.material)}</td><td class="mono">${esc(p.lot)}</td><td class="mono">${esc(p.expiry)}</td><td class="mono">${esc(p.box)}</td><td><span class="chip">${esc(p.position)}</span></td><td class="mono"><b>${fmt(p.qty)} g</b><small class="subqty">/ ${fmt(p.initialQty)} g</small></td><td><span class="badge ${p.packState==='otevřený'?'open':'new'}">${esc(p.packState)}</span></td><td class="row-actions"><button class="icon-action" data-simple-menu="${esc(p.id)}">•••</button></td></tr>`).join(''):'<tr><td colspan="10" class="empty">Žádná data.</td></tr>'}</tbody></table></div></div>`;$('#invMaterial').onchange=e=>{s.material=e.target.value;s.page=1;render()};$('#invState').onchange=e=>{s.packState=e.target.value;s.page=1;render()};$('#selectAll').onchange=e=>{vis.forEach(p=>e.target.checked?s.selected.add(p.id):s.selected.delete(p.id));render()}}
  function warehouse(){ $('#view-warehouse').innerHTML=`<div class="page-title"><div><div class="eyebrow">SKLAD / MAPA</div><h1>Pozice</h1><p>Jedna pozice může obsahovat více boxů a více pytlů.</p></div><button class="btn primary" data-simple="receive">+ Příjem</button></div><div class="warehouse"><div class="warehouse-grid">${db.positions.map(pos=>{const ps=active().filter(p=>p.position===pos.id),q=ps.reduce((z,p)=>z+p.qty,0);return`<button class="slot ${ps.length?'busy':''}" data-slot="${pos.id}"><span>${pos.id}</span>${ps.length?`<b>${fmt(q)} g</b><small>${ps.length} pytle · ${new Set(ps.map(p=>p.box)).size} boxy</small>`:'<small>volná</small>'}</button>`}).join('')}</div></div>`}
  function movements(){const a=db.movements.slice().sort((x,y)=>y.date.localeCompare(x.date)),q=s.q.toLowerCase(),r=a.filter(m=>!q||[m.id,m.type,m.pack,m.from,m.to,m.reason].join(' ').toLowerCase().includes(q));$('#view-movements').innerHTML=`<div class="page-title"><div><div class="eyebrow">AUDIT</div><h1>Pohyby</h1><p>Historie příjmu, výdeje a přesunů.</p></div></div><div class="table-card"><div class="table-scroll"><table><thead><tr><th>ID</th><th>Čas</th><th>Typ</th><th>Pytel</th><th>Trasa</th><th>Množství</th><th>Důvod</th></tr></thead><tbody>${r.length?r.map(m=>`<tr><td class="mono">${m.id}</td><td>${new Date(m.date).toLocaleString('cs-CZ',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</td><td>${m.type}</td><td class="mono">${m.pack}</td><td>${m.from} → ${m.to}</td><td class="mono">${m.qty?`${m.qty>0?'+':''}${fmt(m.qty)} g`:'—'}</td><td>${esc(m.reason||'')}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">Žádné pohyby.</td></tr>'}</tbody></table></div></div>`}
  function materials(){ $('#view-materials').innerHTML=`<div class="page-title"><div><div class="eyebrow">KATALOG</div><h1>Suroviny</h1><p>Referenční seznam materiálů.</p></div><button class="btn primary" data-simple="material">+ Surovina</button></div><div class="table-card"><div class="table-scroll"><table><thead><tr><th>ID</th><th>Název</th><th>Aktivní pytle</th><th>Zásoba</th><th>Minimum</th></tr></thead><tbody>${db.materials.map(m=>`<tr><td class="mono">${m.id}</td><td><b>${esc(m.name)}</b></td><td>${active().filter(p=>p.material===m.id).length}</td><td class="mono">${fmt(active().filter(p=>p.material===m.id).reduce((z,p)=>z+p.qty,0))} g</td><td class="mono">${fmt(m.min)} g</td></tr>`).join('')}</tbody></table></div></div>`}
  function counts(){const c=db.counts.at(-1);$('#view-counts').innerHTML=`<div class="page-title"><div><div class="eyebrow">INVENTURA</div><h1>Inventura</h1><p>Jednoduchý kontrolní seznam aktuální skladové hmotnosti.</p></div><button class="btn primary" data-simple="count">+ Nová inventura</button></div><div class="table-card"><div class="table-scroll"><table><thead><tr><th>Inventura</th><th>Datum</th><th>Položky</th><th>Rozdíly</th><th>Stav</th></tr></thead><tbody>${c?`<tr><td class="mono">${c.id}</td><td>${new Date(c.createdAt).toLocaleString('cs-CZ')}</td><td>${c.items.length}</td><td>${c.items.filter(i=>i.actual!==i.system).length}</td><td>${c.status}</td></tr>`:'<tr><td colspan="5" class="empty">Zatím bez inventur.</td></tr>'}</tbody></table></div></div>`}
  function pager(){const a=s.view==='inventory'?rows():[],pages=Math.max(1,Math.ceil(a.length/s.per));$('#simplePage').textContent=`Strana ${s.page} z ${pages}`;$('#simpleSelection').textContent=`${s.selected.size} vybráno · ${a.length} položek`;$('#firstPage').disabled=s.page===1;$('#prevPage').disabled=s.page===1;$('#nextPage').disabled=s.page===pages;$('#lastPage').disabled=s.page===pages}
  function receive(){modal(`<form class="modal-form" id="f"><div class="modal-head"><div><div class="eyebrow">PŘÍJEM</div><h2>Nové balení</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div>${sel('Surovina','material',db.materials.map(m=>({value:m.id,label:m.name})),db.materials[0]?.id)}<div class="form-grid">${input('Hmotnost (g)','qty','','number','min="0.01" step="0.01" required')}${input('Šarže','lot','','text','required maxlength="60"')}</div><div class="form-grid">${input('Expirace MM/YY','expiry','','text','pattern="^\\d{2}\\/\\d{2}$" placeholder="01/28" required')}${sel('Stav','packState',[{value:'nový',label:'nový'},{value:'otevřený',label:'otevřený'}],'nový')}</div><div class="form-grid">${sel('Box','box',db.boxes.map(b=>({value:b.id,label:b.id})),db.boxes[0]?.id)}${sel('Pozice','position',db.positions.map(p=>({value:p.id,label:p.id})),db.positions[0]?.id)}</div><div class="read-card"><span>Uložení</span><b>Více boxů na stejné pozici je povoleno.</b></div><div class="modal-actions"><button type="button" class="btn" onclick="closeSimple()">Zrušit</button><button class="btn primary">Přijmout</button></div></form>`);$('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),qty=+f.get('qty'),expiry=normExp(f.get('expiry'));if(!qty||qty<=0||!/^[0-9]{2}\/[0-9]{2}$/.test(expiry))return toast('Zkontroluj hmotnost a expiraci MM/YY.');const id=nextPack(),p={id,material:String(f.get('material')),lot:String(f.get('lot')).trim(),expiry,qty,initialQty:qty,box:String(f.get('box')),position:String(f.get('position')),packState:String(f.get('packState'))};db.packs.push(p);db.movements.push({id:next('nextMovement','M-'),date:new Date().toISOString(),type:'Příjem',pack:id,qty,from:'Příjem',to:p.position,reason:'Příjem zásoby'});db.meta.nextPack=(+db.meta.nextPack||1)+1;save('Příjem '+id);close();toast(id+' přijat.')}}
  function issue(id){const p=pack(id);if(!p)return;modal(`<form class="modal-form" id="fi"><div class="modal-head"><div><div class="eyebrow">VÝDEJ</div><h2>${p.id}</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div><div class="detail-grid"><div><span>Surovina</span><b>${esc(mat(p.material)?.name||p.material)}</b></div><div><span>Na skladě</span><b>${fmt(p.qty)} g</b></div><div><span>Šarže</span><b>${esc(p.lot)}</b></div><div><span>Pozice</span><b>${p.position} · Box ${p.box}</b></div></div>${input('Množství (g)','qty','','number','min="0.01" step="0.01" required')}${input('Důvod','reason','Výdej')}<div class="modal-actions"><button type="button" class="btn" onclick="closeSimple()">Zrušit</button><button class="btn primary">Vydat</button></div></form>`);$('#fi').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),q=+f.get('qty');if(!q||q>p.qty)return toast('Neplatné množství.');p.qty-=q;p.packState='otevřený';db.movements.push({id:next('nextMovement','M-'),date:new Date().toISOString(),type:'Výdej',pack:p.id,qty:-q,from:p.position,to:'Výdej',reason:String(f.get('reason')||'Výdej')});save('Výdej '+p.id);close();toast('Vydáno '+fmt(q)+' g.')}}
  function move(id){const p=pack(id);if(!p)return;modal(`<form class="modal-form" id="fm"><div class="modal-head"><div><div class="eyebrow">PŘESUN</div><h2>${p.id}</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div>${sel('Pozice','position',db.positions.map(x=>({value:x.id,label:x.id})),p.position)}${sel('Box','box',db.boxes.map(x=>({value:x.id,label:x.id})),p.box)}${input('Důvod','reason','Změna pozice')}<div class="modal-actions"><button type="button" class="btn" onclick="closeSimple()">Zrušit</button><button class="btn primary">Přesunout</button></div></form>`);$('#fm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),from=p.position;p.position=String(f.get('position'));p.box=String(f.get('box'));db.movements.push({id:next('nextMovement','M-'),date:new Date().toISOString(),type:'Přesun',pack:p.id,qty:0,from,to:p.position,reason:String(f.get('reason')||'Přesun')});save('Přesun '+p.id);close();toast(p.id+' přesunut.')}}
  function detail(id){const p=pack(id);if(!p)return;modal(`<div class="modal-form"><div class="modal-head"><div><div class="eyebrow">DETAIL PYTLE</div><h2>${p.id}</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div><div class="detail-grid"><div><span>Surovina</span><b>${esc(mat(p.material)?.name||p.material)}</b></div><div><span>Šarže</span><b>${esc(p.lot)}</b></div><div><span>Expirace</span><b>${p.expiry}</b></div><div><span>Aktuálně</span><b>${fmt(p.qty)} g</b></div><div><span>Box</span><b>${p.box}</b></div><div><span>Pozice</span><b>${p.position}</b></div><div><span>Stav</span><b>${p.packState}</b></div><div><span>Expirace stav</span><b>${expState(p.expiry)}</b></div></div><div class="modal-actions"><button class="btn" onclick="closeSimple();moveSimple('${p.id}')">Přesun</button><button class="btn primary" onclick="closeSimple();issueSimple('${p.id}')">Výdej</button></div></div>`)}
  function slot(pos){const ps=active().filter(p=>p.position===pos);if(!ps.length)return toast('Pozice je volná.');modal(`<div class="modal-form"><div class="modal-head"><div><div class="eyebrow">POZICE</div><h2>${pos}</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div><div class="slot-list">${ps.map(p=>`<button class="slot-row" onclick="closeSimple();detailSimple('${p.id}')"><span><b>${p.id}</b><small>${esc(mat(p.material)?.name||p.material)} · Box ${p.box}</small></span><strong>${fmt(p.qty)} g</strong></button>`).join('')}</div></div>`)}
  function materialNew(){modal(`<form class="modal-form" id="fat"><div class="modal-head"><div><div class="eyebrow">KATALOG</div><h2>Nová surovina</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div>${input('Název','name')}${input('Minimum (g)','min','','number','min="0" step="0.01" required')}<div class="modal-actions"><button type="button" class="btn" onclick="closeSimple()">Zrušit</button><button class="btn primary">Uložit</button></div></form>`);$('#fat').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')).trim(),min=+f.get('min');if(!name)return;db.materials.push({id:next('nextMaterial','S-'),name,min});save('Nová surovina '+name);close();toast('Surovina přidána.')}}
  function cycle(){const c={id:next('nextCount','IC-'),createdAt:new Date().toISOString(),status:'OPEN',items:active().map(p=>({pack:p.id,position:p.position,system:p.qty,actual:p.qty}))};db.counts.push(c);save('Nová inventura '+c.id);toast('Inventura založena.')} 
  function settings(){modal(`<div class="modal-form"><div class="modal-head"><div><div class="eyebrow">SYSTÉM</div><h2>Nastavení</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div><div class="read-card"><span>Lokální fronta</span><b>${(JSON.parse(localStorage.getItem('botanic-wms-outbox-v2')||'[]')).length} změn</b></div><div class="modal-actions"><button class="btn" onclick="toggleThemeSimple()">Přepnout vzhled</button><button class="btn" onclick="backupSimple()">Záloha JSON</button><button class="btn" onclick="closeSimple()">Hotovo</button></div></div>`)}
  function backup(){const b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='botanic-sklad-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function toggleTheme(){s.theme=s.theme==='dark'?'light':'dark';localStorage.setItem('botanic-theme',s.theme);render()}
  function sort(){s.dir=s.dir==='asc'?'desc':'asc';render();toast('Řazení změněno.')}
  function wire(){
    $('#simpleSearch').addEventListener('input',e=>{s.q=e.target.value;s.page=1;render()});$('#simpleRows').onchange=e=>{s.per=+e.target.value;s.page=1;render()};$('#simpleSortButton').onclick=sort;$('#simpleViewButton').onclick=()=>{document.body.classList.toggle('compact');toast(document.body.classList.contains('compact')?'Kompaktní zobrazení':'Standardní zobrazení')};$('#simpleReceive').onclick=receive;$('#simpleSettings').onclick=settings;$('#simpleTheme').onclick=toggleTheme;$('#simpleExport').onclick=()=>window.XLSX?exportXlsx():toast('Exportní knihovna není načtena.');$('#simpleImport').onclick=()=>$('#simpleFile').click();$('#simpleFile').onchange=e=>{if(e.target.files?.[0])importXlsx(e.target.files[0]);e.target.value=''};$('#firstPage').onclick=()=>{s.page=1;render()};$('#prevPage').onclick=()=>{s.page=Math.max(1,s.page-1);render()};$('#nextPage').onclick=()=>{s.page++;render()};$('#lastPage').onclick=()=>{s.page=Math.ceil(rows().length/s.per);render()};document.addEventListener('click',e=>{const nav=e.target.closest('[data-simple-view]');if(nav){s.view=nav.dataset.simpleView;s.page=1;render();return}const menu=e.target.closest('[data-simple-menu]');if(menu){const id=menu.dataset.simpleMenu;modal(`<div class="modal-form"><div class="modal-head"><div><div class="eyebrow">AKCE</div><h2>${id}</h2></div><button class="icon-action" type="button" onclick="closeSimple()">×</button></div><button class="btn" onclick="closeSimple();detailSimple('${id}')">Otevřít detail</button><button class="btn" onclick="closeSimple();moveSimple('${id}')">Přesunout</button><button class="btn primary" onclick="closeSimple();issueSimple('${id}')">Výdej</button></div>`);return}const a=e.target.closest('[data-simple]');if(a){const t=a.dataset.simple;if(t==='receive')receive();if(t==='issue'){const p=active()[0];if(p)issue(p.id)}if(t==='move'){const p=active()[0];if(p)move(p.id)}if(t==='material')materialNew();if(t==='count')cycle();return}const slotBtn=e.target.closest('[data-slot]');if(slotBtn){slot(slotBtn.dataset.slot)}});document.addEventListener('change',e=>{if(e.target.classList.contains('row-check')){const id=e.target.closest('tr').dataset.id;e.target.checked?s.selected.add(id):s.selected.delete(id);render()}});window.addEventListener('online',render);window.addEventListener('offline',render)}
  function exportXlsx(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(db.packs.map(p=>({ID_pytle:p.id,Nazev_suroviny:mat(p.material)?.name||p.material,Sarze:p.lot,Expirace:p.expiry,Box:p.box,Pozice:p.position,Aktualni_hmotnost_g:p.qty,Stav:p.packState}))), 'SKLAD');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(db.movements),'POHYBY_LOG');XLSX.writeFile(wb,'botanic-sklad.xlsx');toast('Export vytvořen.')}
  function importXlsx(file){const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),sh=wb.Sheets.SKLAD;if(!sh)throw new Error('Chybí list SKLAD.');const rows=XLSX.utils.sheet_to_json(sh,{defval:''});db.packs=rows.map((x,i)=>({id:String(x.ID_pytle||`P-${new Date().getFullYear()}-${String(i+1).padStart(3,'0')}`),material:String(x.ID_surovina||db.materials.find(m=>m.name===x.Nazev_suroviny)?.id||db.materials[0]?.id),lot:String(x.Sarze||'IMPORT'),expiry:normExp(x.Expirace||'01/28'),box:String(x.Box||'1').replace(/^B-/i,''),position:String(x.Pozice||'A1'),qty:+x.Aktualni_hmotnost_g||0,initialQty:+x.Puvodni_g||+x.Aktualni_hmotnost_g||0,packState:String(x.Stav||'nový')==='otevřený'?'otevřený':'nový'}));if(ensure())save('Import XLSX'),toast('Import dokončen.')}catch(err){toast('Import selhal: '+err.message)}};r.readAsArrayBuffer(file)}
  window.closeSimple=close;window.receiveSimple=receive;window.issueSimple=issue;window.moveSimple=move;window.detailSimple=detail;window.backupSimple=backup;window.toggleThemeSimple=toggleTheme;window.openIssue=issue;window.openMove=move;window.openPack=detail;
  wire();render();
})();
